# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Game

on: [release, pull_request, workflow_dispatch]

env:
  # Configuration type to build.
  BUILD_CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    # On Windows runners, let's ensure to have the Developer Command Prompt environment setup correctly.
    # As used here the Developer Command Prompt created is targeting x64 and using the default the Windows SDK.
    - uses: ilammy/msvc-dev-cmd@v1
    
    - name: Prepare to Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cmake -S . -B ./BUILD

    - name: Compile
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cd ./BUILD && make

  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install some stuff!
      run: sudo dpkg --add-architecture i386; sudo apt install libc libstdc++=6 clang lib32stdc++-7-dev lib32z1-dev libc6-dev-i386 linux-libc-dev:i386 g++-multilib
      
    - name: Prepare to build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cmake -S . -B ./BUILD

    - name: Compile
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cd ./BUILD && make
