# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Game

on: [release, pull_request, workflow_dispatch]

env:
  # Configuration type to build.
  BUILD_CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  Windows:
    if: false # Disable Windows Compilation, Reason: make doesn't compile, needs a contributor with Windows system to fix it.
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    # On Windows runners, let's ensure to have the Developer Command Prompt environment setup correctly.
    # As used here the Developer Command Prompt created is targeting x64 and using the default the Windows SDK.
    - uses: ilammy/msvc-dev-cmd@v1
    
    - name: Prepare to Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cmake -S . -B ./BUILD

    - name: Compile
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cd ./BUILD && make

  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: GCC G++ 4.2.4
      run: |
        sudo apt install g++-multilib
        sudo wget https://bigsearcher.com/mirrors/gcc/releases/gcc-4.2.4/gcc-g++-4.2.4.tar.gz
        sudo tar xzf gcc-g++-4.2.4.tar.gz
        cd ./gcc-4.2.4
        ./configure
        make
        sudo make install
      
    - name: Prepare to build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cmake -S . -B ./BUILD

    - name: Compile
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cd ./BUILD && make
